from MyLeague import MyLeague
league_object = MyLeague.createLeague()

def main():
    # league_object.printSeasonMatchupResults()
    # print()
    # league_object.LeagueStandings() 
    # print()
    # league_object.DivisionStandings(1)
    # print()
    # league_object.DivisionStandings(2)
    # print()
    # league_object.LeagueDraftResults()
    # print()
    # league_object.printAllBestTeamStat()
    # print()
    # league_object.printTeamRosters()  
    # print()
    # league_object.printTeamByPoints()
    # print()
    # league_object.printTeamByAvgPoints() 
    # print()
    # league_object.printDraftedTeam()
    # print()
    # league_object.printPlayersByAvgPoints()
    # print()
    # league_object.LeagueDraftGrade()
    league_object.StreakReport(True, league_object.free_agents)
    print()
    league_object.StreakReport(True, league_object.teams)
main()
